"""Ninth

Revision ID: 53bdbcd8ca6f
Revises: ba53a9cf59a4
Create Date: 2024-02-27 08:59:42.884068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bdbcd8ca6f'
down_revision: Union[str, None] = 'ba53a9cf59a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
