"""Fifth

Revision ID: 773dd955e2fc
Revises: b097e5fb7fbf
Create Date: 2024-02-19 11:45:28.943545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773dd955e2fc'
down_revision: Union[str, None] = 'b097e5fb7fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'timestamp')
    # ### end Alembic commands ###
