"""test

Revision ID: 788a8171f599
Revises: 4829e522ee89
Create Date: 2024-02-27 09:45:39.122377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788a8171f599'
down_revision: Union[str, None] = '4829e522ee89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('date_and_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('currency', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('currency', 'date_and_time')
    # ### end Alembic commands ###
