"""Tenthg

Revision ID: b881395958f2
Revises: 53bdbcd8ca6f
Create Date: 2024-02-27 09:41:21.797441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b881395958f2'
down_revision: Union[str, None] = '53bdbcd8ca6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_testt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_testt_id'), 'currency_testt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_testt_id'), table_name='currency_testt')
    op.drop_table('currency_testt')
    # ### end Alembic commands ###
