"""Eighthh

Revision ID: ba53a9cf59a4
Revises: d47ab83a1da9
Create Date: 2024-02-27 08:54:19.267104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba53a9cf59a4'
down_revision: Union[str, None] = 'd47ab83a1da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_test_id'), 'currency_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_test_id'), table_name='currency_test')
    op.drop_table('currency_test')
    # ### end Alembic commands ###
